# Generated by Django 4.2 on 2023-05-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productsmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='src',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
